import '@styles/globals.css';

import type { Metadata } from 'next';
import { Toaster } from '@ui/toaster';
import { Inter } from 'next/font/google';
import NextTopLoader from 'nextjs-toploader';
import { ClerkProvider, ThemeProvider } from '@providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={inter.className}>
        <NextTopLoader showSpinner={false} />
        <ThemeProvider>
          <ClerkProvider>{children}</ClerkProvider>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
